package(default_visibility = [
    "//monolith/integration_test:__subpackages__",
    "//monolith/agent_service:__subpackages__",
])

filegroup(
    name = "test_data",
    srcs = [
        "inst.pbtext", 
        "inst.json", 
        "inst.dump",
    ]
)
