load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "fountain_dataset_ops",
    visibility = ["//visibility:public"],
)

py_library(
    name = "fountain_lib",
    visibility = ["//visibility:public"],
)
