package(default_visibility = [
    "//monolith/integration_test:__subpackages__",
    "//monolith/native_training:__subpackages__",
])

filegroup(
    name = "test_feature_lists",
    srcs = [
    ],
)
